# NumPy Fundamentals

### 1. Run the following cells:

In [1]:
import numpy as np

In [49]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array([10, 11, 12, 13, 14])

In [50]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [51]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 2. Display the first element (not necessarily individual element) for each of the 3 arrays we defined above.

In [52]:
array_1D[0]

10

In [53]:
array_2D[0]

array([20, 30, 40, 50, 60])

In [54]:
array_3D[0]

array([[ 1,  2,  3,  4,  5],
       [11, 21, 31, 41, 51]])

### 3. Call the first individual element of the each of the 3 arrays. 

In [55]:
array_1D[0]

10

In [56]:
array_2D[0,0]

20

In [57]:
array_3D[0,0,0]

1

### 4. Uses negative indices to display the last element of each array.

In [58]:
array_1D[-1]

14

In [59]:
array_2D[-1,-1]

55

In [60]:
array_3D[-1,-1,-1]

5

### 5. Set the penultimate (second-to-last) <i> individual </i> element of each array equal to 10. Then display the variables to check your work. 
(<b>Hint</b>: If it's the penultimate individual element of the 2-D/3-D array, it needs to be in the last row of the 2-D array)

In [61]:
array_1D[-2] = 10
array_1D

array([10, 11, 12, 10, 14])

In [62]:
array_2D[-1,-2] = 10
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 10, 55]])

In [63]:
array_3D[-1,-1,-2] = 10
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 10,  5]]])

### 6. Set the last column of the 2-D array to 100. Then display the variables to check your work. 

In [64]:
array_2D[:,-1] = 100
array_2D

array([[ 20,  30,  40,  50, 100],
       [ 43,  54,  65,  76, 100],
       [ 11,  22,  33,  10, 100]])

### 7. Set all the values of the 3-D array to 1000. Then display the variables to check your work. 

In [65]:
array_3D[:] = 1000
array_3D

array([[[1000, 1000, 1000, 1000, 1000],
        [1000, 1000, 1000, 1000, 1000]],

       [[1000, 1000, 1000, 1000, 1000],
        [1000, 1000, 1000, 1000, 1000]]])

### 8. Run the next 3 cells to re-define the 3 arrays, since we altered their contents. 

In [66]:
array_1D = np.array([10,11,12,13,14])
array_1D

array([10, 11, 12, 13, 14])

In [67]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [68]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 9. Add 2 to every element of the 3 arrays without overwriting their values.

In [69]:
array_1D + 2

array([12, 13, 14, 15, 16])

In [70]:
array_2D + 2

array([[22, 32, 42, 52, 62],
       [45, 56, 67, 78, 89],
       [13, 24, 35, 46, 57]])

In [71]:
array_3D + 2

array([[[ 3,  4,  5,  6,  7],
        [13, 23, 33, 43, 53]],

       [[13, 14, 15, 16, 17],
        [53, 54, 55, 56,  7]]])

### 10. Multiply the values of each array by 100 without overwriting their values.

In [72]:
array_1D * 100

array([1000, 1100, 1200, 1300, 1400])

In [73]:
array_1D * 100

array([1000, 1100, 1200, 1300, 1400])

In [74]:
array_3D * 100

array([[[ 100,  200,  300,  400,  500],
        [1100, 2100, 3100, 4100, 5100]],

       [[1100, 1200, 1300, 1400, 1500],
        [5100, 5200, 5300, 5400,  500]]])

### 11. Add up <i>array_1D</i> and the first row of <i>array_2D</i>

In [75]:
array_1D + array_2D[0]

array([30, 41, 52, 63, 74])

### 12. Multiply <i>array_1D</i> and the first row of <i>array_2D</i>

In [76]:
array_1D * array_2D[0]

array([200, 330, 480, 650, 840])

### 13. Multiply  of the first row of <i>array_2D</i> and the first row of the first array of <i> array_3D </i>

In [77]:
array_2D[0] * array_3D[0,0]

array([ 20,  60, 120, 200, 300])

### 14. Subtract <i> array_1D </i> from the first row of <i>array_2D</i>

In [78]:
array_2D[0] - array_1D 

array([10, 19, 28, 37, 46])

### 15. Subtract the first row of <i>array_2D</i> from  <i> array_1D </i> 

In [79]:
array_1D - array_2D[0]

array([-10, -19, -28, -37, -46])

### 16. Alter the code in the next 3 cells to re-define the 3 arrays as the following datatypes:
    A) array_1D -> NumPy Strings
    B) array_2D -> Complex Numbers
    C) array_3D -> 64-bit Floats
    
   (<b>Hint</b>: The datatypes are the following: <i>np.str</i>, <i>np.complex</i>, <i>np.float64</i>)

In [80]:
array_1D = np.array([10,11,12,13,14])
array_1D

array([10, 11, 12, 13, 14])

In [81]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [82]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 17. Now run the next 3 cells to re-define the 3 arrays as 32-bit floats, since we want to run some more computations on them

In [83]:
array_1D = np.array([10,11,12,13,14], dtype = np.float32)
array_1D

array([10., 11., 12., 13., 14.], dtype=float32)

In [84]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype = np.float32)
array_2D

array([[20., 30., 40., 50., 60.],
       [43., 54., 65., 76., 87.],
       [11., 22., 33., 44., 55.]], dtype=float32)

In [85]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]], dtype = np.float32)
array_3D

array([[[ 1.,  2.,  3.,  4.,  5.],
        [11., 21., 31., 41., 51.]],

       [[11., 12., 13., 14., 15.],
        [51., 52., 53., 54.,  5.]]], dtype=float32)

### 18. Use broadcasting to subtract  <i>array_1D</i> from every row of <i> array_2D </i> 
   (<b>Hint</b>: You **don't** need a function to do this.)

In [86]:
array_2D - array_1D

array([[10., 19., 28., 37., 46.],
       [33., 43., 53., 63., 73.],
       [ 1., 11., 21., 31., 41.]], dtype=float32)

### 19. Use broadcasting to divide all rows of <i>array_3D</i> by <i> array_1D </i> 

In [87]:
array_3D / array_1D

array([[[0.1       , 0.18181819, 0.25      , 0.30769232, 0.35714287],
        [1.1       , 1.9090909 , 2.5833333 , 3.1538463 , 3.642857  ]],

       [[1.1       , 1.0909091 , 1.0833334 , 1.0769231 , 1.0714285 ],
        [5.1       , 4.7272725 , 4.4166665 , 4.1538463 , 0.35714287]]],
      dtype=float32)

### 19. Use broadcasting to multiply all rows of <i>array_3D</i>  and the last row of <i> array_2D </i> 

In [88]:
array_3D * array_2D[-1]

array([[[  11.,   44.,   99.,  176.,  275.],
        [ 121.,  462., 1023., 1804., 2805.]],

       [[ 121.,  264.,  429.,  616.,  825.],
        [ 561., 1144., 1749., 2376.,  275.]]], dtype=float32)

### 20. Cast all the result **into integers**
   (<b>Hint</b>: You can use the np.array() function here)

In [89]:
np.array(array_3D * array_2D[-1], dtype = np.int32)

array([[[  11,   44,   99,  176,  275],
        [ 121,  462, 1023, 1804, 2805]],

       [[ 121,  264,  429,  616,  825],
        [ 561, 1144, 1749, 2376,  275]]])

### 21. Use axis argument of the np.mean() function to **find the mean** for every column of the 2-D array

In [90]:
np.mean(array_2D, axis = 0)

array([24.666666, 35.333332, 46.      , 56.666668, 67.333336],
      dtype=float32)

### 22. Let's use axis argument of the np.mean() function to find the mean for every column of the 3-D array
   (<b>Hint</b>: Make sure you define the correct axis)

In [91]:
array_3D[0,1,0] = 7             # diubah valuenya agar contohnya tidak membingungkan
np.array(array_3D, dtype = int)

array([[[ 1,  2,  3,  4,  5],
        [ 7, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

**axis = 0** -> baris pertama di array pertama dimeankan dengan baris pertama array kedua  
lalu baris kedua di array pertama dimeankan dengan baris kedua di array kedua    
(1 + 11) / 2 lalu (2 + 12) / 2 dan seterusnya

In [92]:
np.mean(array_3D, axis = 0)

array([[ 6. ,  7. ,  8. ,  9. , 10. ],
       [29. , 36.5, 42. , 47.5, 28. ]], dtype=float32)

**axis = 1** -> baris pertama array pertama dimeankan dengan baris kedua array pertama
lalu baris pertama di array kedua dimeankan dengan baris kedua di array kedua
axis = 1 memproses masing-masing array terlebih dahulu, yaitu mean dari array pertama lalu mean dari array kedua       
(1 + 7) / 2 lalu (2 + 21) / 2 dan seterusnya