# Working with Arrays

In [3]:
import numpy as np

## Slicing

In [ ]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

### Basic Slicing

In [ ]:
matrix_A[:]

## The default start and stop for slicing are the origin and the end of the array. 
## Hence, [:] includes the entire array. 

In [ ]:
type(matrix_A[:,:])

## [:,:] -> All rows, and all columns.

In [ ]:
matrix_A[:2]

# [:2] -> All the rows up to the 3rd one (excluding the third one).
# hasilnya menampilkan semua data, karena matrix_A memang hanya terdiri dari dua baris

In [ ]:
matrix_A[1]

# menampilkan baris dengan index 1 (baris kedua)

In [ ]:
matrix_A[:-1]

# [:-1] -> Semua baris kecuali baris index -1 (baris terakhir)

In [ ]:
matrix_A[:,1:]

# Semua baris
# Kolom dimulai dari index ke 1 (kolom kedua) dan seterusnya

In [ ]:
matrix_A

In [ ]:
matrix_A[1:,1:]

# All the rows after the first one and all the column after the first one. 

### **Stepwise** Slicing

In [4]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

Syntaxnya adalah [ **start** : **stop** : **step** (kelipatan) ]

In [5]:
matrix_B[::2,::2]

# Mulai dari baris pertama (startnya tidak diberi nilai), berhenti saat selesai (stopnya tidak diberi nilai)
# Barisnya kelipatan 2 (Baris pertama, kemudian baris ketiga)
# Hal yang sama untuk kolom

array([[1, 1, 0],
       [4, 3, 0]])

In [6]:
matrix_B[-1::-1,::2]

# A negative step means we're going through the array in reverse.
# Mulai dari baris terakhir, kelipatan -1 (Jika startnya negatif, maka stepnya juga harus negatif)

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

In [14]:
matrix_B[-1::1,::2]

# Jika stepnya positif, maka yang ditampilkan hanya baris terakhir saja
# Cara bacanya "Tampilkan baris terakhir (minus) dengan step 1"
# Baris yang ditampilkan adalah baris terakhir, jadi kelipatan 1 setelah baris terakhir ya TIDAK ADA BARIS

array([[4, 3, 0]])

### **Conditional** Slicing

In [15]:
matrix_C = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_C

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [16]:
matrix_C[:,0]

array([1, 3, 4])

In [18]:
matrix_C[:,0] > 2

# Returns True/False based on whether the individual element satisfies the condition. 

array([False,  True,  True])

Terlepas dari berapa dimensi array, jika menggunakan conditional maka Python akan mengembalikannya **satu dimensi**  
Karena Python tidak mengetahui dimensi yang tepat untuk return valuenya berapa

In [20]:
matrix_C[matrix_C[:,:] % 2 == 0]

# Returns the actual values which satisfy the condition, not simply True or False.
# Jadi satu dimensi

array([2, 0, 6, 6, 4, 4, 8, 0])

In [19]:
matrix_C[(matrix_C[:,:] % 2 == 0) | (matrix_C[:,:] <= 4)]

# We can have more complex conditions, which are comprised of several smaller conditions. 
# & -> Both conditions must be met. 
# | -> Either condition can be met. 

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 8, 0])

## Dimensions and the **Squeeze** Function

In [21]:
matrix_D = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [22]:
type(matrix_D[0,0])

# Fixing both indices. 
# 0-D array

numpy.int32

In [23]:
print(matrix_D[0,0])

1


In [24]:
type(matrix_D[0,0:1])

# 1 index is fixed, the second one is a slice
# 1-D array

numpy.ndarray

In [25]:
print(matrix_D[0,0:1])

[1]


In [26]:
type(matrix_D[0:1,0:1])

# Both indices are ranges (slices)
# 2-D array

numpy.ndarray

In [27]:
print(matrix_D[0:1,0:1])

[[1]]


Berbeda jumlah **:** (colon) saja, Python membacanya beda dimensi  
Bisa dilihat di atas, ada 0-D (scalar) 1-D (Vector) dan 2-D (Matrix) 

In [ ]:
print(matrix_D[0,0].shape)
print(matrix_D[0,0:1].shape)
print(matrix_D[0:1,0:1].shape)

# Same value stored in 3 different ways -> 0-D, 1-D and 2-D array

Maka ada fungsi ***Squeeze*** untuk menghapus dimensi yang tidak diperlukan agar data kita konsisten

In [29]:
print(matrix_D[0:1,0:1].squeeze())

## Removes excess dimensions
## Yang tadinya matrix, jadi scalar karena valuenya hanya 1 saja

1


In [ ]:
np.squeeze(matrix_D[0:1,0:1])

## The function is equivalent to the method. 

In [30]:
print(matrix_D[0,0].squeeze().shape)
print(matrix_D[0,0:1].squeeze().shape)
print(matrix_D[0:1,0:1].squeeze().shape)

## All excess dimensions are lost and our outputs are aligned.  
## Squeeze di atas adalah method, jadi harus menempel langsung pada code matrix
## Sedangkan .shape adalah function

()
()
()
